package exception

var (
	ErrUnknown               = New().WithErrorCode(ErrCodeUnknown).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeUnknown]).WithMessageKey(UnknownErrMsgKey)
	ErrBadRequest            = New().WithErrorCode(ErrCodeInvalidArgument).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeInvalidArgument]).WithMessageKey(BadRequestErrMsgKey)
	ErrNotfound              = New().WithErrorCode(ErrCodeNotFound).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeNotFound]).WithMessageKey(NotFoundErrMsgKey)
	ErrTooManyRequests       = New().WithErrorCode(ErrCodeTooManyRequests).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeTooManyRequests]).WithMessageKey(TooManyRequestsErrMsgKey)
	ErrTimeout               = New().WithErrorCode(ErrCodeTimeout).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeTimeout]).WithMessageKey(TimeoutErrMsgKey)
	ErrInternal              = New().WithErrorCode(ErrCodeSomethingWentWrong).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeSomethingWentWrong]).WithMessageKey(SomethingWentWrongErrMsgKey)
	ErrSerializationFailed   = New().WithErrorCode(ErrCodeSerializationFailure).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeSerializationFailure]).WithMessageKey(SerializationFailureErrMsgKey)
	ErrDeserializationFailed = New().WithErrorCode(ErrCodeDeserializationFailure).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeDeserializationFailure]).WithMessageKey(DeserializationFailureErrMsgKey)
	ErrInvalidAmount         = New().WithErrorCode(ErrCodeInvalidAmount).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeInvalidAmount]).WithMessageKey(InvalidAmountErrMsgKey)
	ErrAlreadyExists         = New().WithErrorCode(ErrCodeAlreadyExists).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeAlreadyExists]).WithMessageKey(AlreadyExistsErrMsgKey)
	ErrMissingTranslationKey = New().WithErrorCode(ErrCodeMissingTranslationKey).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeMissingTranslationKey]).WithMessageKey(MissingTranslationErrMsgKey)
	ErrMissingI18nResource   = New().WithErrorCode(ErrCodeMissingI18nResource).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeMissingI18nResource]).WithMessageKey(MissingI18nResourceErrMsgKey)
	ErrLoadingI18nResource   = New().WithErrorCode(ErrCodeLoadingI18nResource).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeLoadingI18nResource]).WithMessageKey(LoadingI18nResourceErrMsgKey)
	ErrInvalidConfig         = New().WithErrorCode(ErrCodeInvalidConfig).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeInvalidConfig]).WithMessageKey(InvalidConfigErrMsgKey)
	ErrDuplicateRequest      = New().WithErrorCode(ErrCodeDuplicateRequest).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeDuplicateRequest]).WithMessageKey(DuplicateRequestErrMsgKey)
	ErrActionFailed          = New().WithErrorCode(ErrCodeActionFailed).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeActionFailed]).WithMessageKey(SomethingWentWrongErrMsgKey)
	ErrInsufficientBalance   = New().WithErrorCode(ErrCodeInsufficientBalance).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeInsufficientBalance]).WithMessageKey(InsufficientBalanceErrMsgKey)
	ErrNotImplemented        = New().WithErrorCode(ErrCodeNotImplemented).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeNotImplemented]).WithMessageKey(NotImplementedErrMsgKey)
	ErrInvalidArgument       = New().WithErrorCode(ErrCodeInvalidArgument).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeInvalidArgument]).WithMessageKey(InvalidArgumentErrMsgKey)
	ErrForeignKeyViolation   = New().WithErrorCode(ErrCodeDBForeignKeyViolation).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeDBForeignKeyViolation]).WithMessageKey(SomethingWentWrongErrMsgKey)
	ErrNullViolation         = New().WithErrorCode(ErrCodeDBNullViolation).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeDBNullViolation]).WithMessageKey(SomethingWentWrongErrMsgKey)
	ErrRecordNotFound        = New().WithErrorCode(ErrCodeDBRecordNotFound).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeDBRecordNotFound]).WithMessageKey(DBRecordNotFoundErrMsgKey)
	ErrInvalidTransaction    = New().WithErrorCode(ErrCodeDBInvalidTransaction).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeDBInvalidTransaction]).WithMessageKey(SomethingWentWrongErrMsgKey)
	ErrDuplicateRecord       = New().WithErrorCode(ErrCodeDBDuplicateRecord).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeDBDuplicateRecord]).WithMessageKey(DBDuplicateRecordErrMsgKey)
	ErrDBInternal            = New().WithErrorCode(ErrCodeDBInternal).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeDBInternal]).WithMessageKey(SomethingWentWrongErrMsgKey)
	ErrKafkaNewPubSub        = New().WithErrorCode(ErrCodeKafkaNewPubSub).WithHttpStatusCode(ErrorCodeToHTTPStatus[ErrCodeDBInternal]).WithMessageKey(SomethingWentWrongErrMsgKey)
)
